In [1]:
import numpy as np

In [2]:
arr1 = np.random.rand(3, 4)
mean_arr1 = np.mean(arr1, axis=1)
std_arr1 = np.std(arr1, axis=1)
var_arr1 = np.var(arr1, axis=1)

print("a. Arr1:")
print(arr1)
print("Mean along axis 1:", mean_arr1)
print("Standard Deviation along axis 1:", std_arr1)
print("Variance along axis 1:", var_arr1)
print()

a. Arr1:
[[0.90275892 0.09285054 0.66712098 0.04127659]
 [0.72453498 0.61390353 0.95505435 0.30557176]
 [0.63063191 0.8569399  0.66533841 0.01193254]]
Mean along axis 1: [0.42600176 0.64976615 0.54121069]
Standard Deviation along axis 1: [0.36893057 0.23374515 0.31749966]
Variance along axis 1: [0.13610977 0.05463679 0.10080604]



In [3]:
# b. Create a 2D array, print shape, type, and data type, then reshape based on user inputs
m = int(input("Enter number of rows (m): "))
n = int(input("Enter number of columns (n): "))
arr2 = np.random.randint(0, 10, size=(m, n))
print("b. Original Array:")
print(arr2)
print("Shape:", arr2.shape)
print("Type:", type(arr2))
print("Data Type:", arr2.dtype)

# Check if the new shape is valid
n_new = int(input("Enter new number of columns (n): "))
m_new = int(input("Enter new number of rows (m): "))
if m * n != m_new * n_new:
    print("Invalid new shape. The total number of elements must remain the same.")
else:
    arr2_reshaped = np.reshape(arr2, (m_new, n_new))
    print("Reshaped Array:")
    print(arr2_reshaped)
    print()

Enter number of rows (m):  2
Enter number of columns (n):  2


b. Original Array:
[[4 4]
 [2 7]]
Shape: (2, 2)
Type: <class 'numpy.ndarray'>
Data Type: int32


Enter new number of columns (n):  2
Enter new number of rows (m):  2


Reshaped Array:
[[4 4]
 [2 7]]



In [4]:
# c. Test whether elements of a 1D array are zero, non-zero, and NaN, and record indices
arr3 = np.array([1, 0, 5, 0, np.nan, 8])
zero_indices = np.where(arr3 == 0)[0]
nonzero_indices = np.where(arr3 != 0)[0]
nan_indices = np.where(np.isnan(arr3))[0]

print("c. Array:")
print(arr3)
print("Zero indices:", zero_indices)
print("Non-zero indices:", nonzero_indices)
print("NaN indices:", nan_indices)
print()


c. Array:
[ 1.  0.  5.  0. nan  8.]
Zero indices: [1 3]
Non-zero indices: [0 2 4 5]
NaN indices: [4]



In [5]:
# d. Create three random arrays, perform operations, find Covariance and Correlation
array1 = np.random.rand(5)
array2 = np.random.rand(5)
array3 = np.random.rand(5)

array4 = array3 - array2
array5 = 2 * array1

covariance = np.cov(array1, array4)[0, 1]
correlation = np.corrcoef(array1, array5)[0, 1]

print("d. Arrays:")
print("Array1:", array1)
print("Array2:", array2)
print("Array3:", array3)
print("Array4 (Array3 - Array2):", array4)
print("Array5 (2 * Array1):", array5)
print("Covariance between Array1 and Array4:", covariance)
print("Correlation between Array1 and Array5:", correlation)
print()


d. Arrays:
Array1: [0.20643661 0.94448318 0.59018894 0.85562986 0.94378237]
Array2: [0.40879274 0.88995506 0.25097372 0.05561573 0.20049169]
Array3: [0.71106125 0.63443171 0.50416314 0.88866027 0.59542126]
Array4 (Array3 - Array2): [ 0.30226851 -0.25552335  0.25318942  0.83304454  0.39492957]
Array5 (2 * Array1): [0.41287322 1.88896636 1.18037787 1.71125973 1.88756475]
Covariance between Array1 and Array4: -0.006480454495664835
Correlation between Array1 and Array5: 0.9999999999999998



In [6]:
# e. Create two random arrays, find sum of the first half and product of the second half
array6 = np.random.rand(10)
array7 = np.random.rand(10)

sum_first_half = np.sum(array6[:5])
product_second_half = np.prod(array7[5:])

print("e. Arrays:")
print("Array6:", array6)
print("Array7:", array7)
print("Sum of the first half of Array6:", sum_first_half)
print("Product of the second half of Array7:", product_second_half)
print()

e. Arrays:
Array6: [0.03099843 0.624695   0.6924307  0.5639953  0.42382855 0.66093137
 0.53757432 0.28896824 0.87523832 0.66184512]
Array7: [0.22748819 0.02627007 0.09265107 0.70066615 0.41118334 0.53539357
 0.24248592 0.98785053 0.07044121 0.70552954]
Sum of the first half of Array6: 2.335947980386977
Product of the second half of Array7: 0.006373719381495896



In [7]:
# f. Create an array with random values and determine memory size
array8 = np.random.rand(4, 5)
memory_size = array8.nbytes

print("f. Array:")
print(array8)
print("Memory size of the array (in bytes):", memory_size)
print()



f. Array:
[[0.64265201 0.92096341 0.94873189 0.20076718 0.54064431]
 [0.64338478 0.80851699 0.88941921 0.86061896 0.38540933]
 [0.74790136 0.74467331 0.0087928  0.49750615 0.52877977]
 [0.36416098 0.07516967 0.2549907  0.54765163 0.82310767]]
Memory size of the array (in bytes): 160



In [8]:
# g. Create a 2D array, swap rows, reverse a specified column, and store in another variable
m_g = 4
n_g = 3
array9 = np.random.randint(10, 100, size=(m_g, n_g))
print("g. Original Array:")
print(array9)
# Swap rows 0 and 1
array9_swapped = array9.copy()
array9_swapped[0, :], array9_swapped[1, :] = array9_swapped[1, :], array9_swapped[0, :].copy()

# Reverse column 2
array9_reversed_column = array9_swapped.copy()
array9_reversed_column[:, 2] = array9_reversed_column[::-1, 2]

print("Array after swapping rows 0 and 1:")
print(array9_swapped)
print("Array after reversing column 2:")
print(array9_reversed_column)

g. Original Array:
[[12 33 25]
 [21 65 93]
 [18 80 32]
 [79 82 65]]
Array after swapping rows 0 and 1:
[[21 65 93]
 [12 33 25]
 [18 80 32]
 [79 82 65]]
Array after reversing column 2:
[[21 65 65]
 [12 33 32]
 [18 80 25]
 [79 82 93]]
